### ISSUE TITLE
Very slow on degree 4 extensions

### ISSUE THREAD

**Issue by sashakolpakov** [bottine/VinbergsAlgorithmNF#12]
The following code makes it clog for a long time (no response since > 1 hour). Here -a = \sqrt{2}+\sqrt{3}.

> Qx, x = PolynomialRing(FlintQQ, "x");
> K,a = Hecke.NumberField(1 - 10*x^2 + x^4);
> m = [1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 a+1];
> vd = VA.VinbergData(K,m)
> (status, (roots,dict,das)) = VA.next_n_roots!(vd,n=10)

**Comment by bottine** [comment]
Mmh, it's probably a hard field for computations. I'll investigate when time allows!

**Comment by sashakolpakov** [comment]
In fact, it will be nice to find anything over Q(\sqrt{6}), Q(\sqrt{2},\sqrt{3}) and Q(\sqrt{2},\sqrt{5}). Some Q(\cos(2\pi/m)) fields are also interesting: m=9, 11, 15, 16, 20. This is for dimensions n = 3 or, better, n =4.

**Comment by bottine** [comment]
Q(\sqrt{6}) should not be too much trouble, but I think with larger extension degree than 2/3, we will quickly get to the point where the implementation fails miserably.

**Comment by sashakolpakov** [comment]
>> Q(\sqrt{6}) should not be too much trouble

Not sure even about this! (after a few tries in dim n=3) It works, yes, but finds no *reflective* form so far.

**Comment by sashakolpakov** [comment]
> we will quickly get to the point where the implementation fails miserably 

Why would it fail so badly ? Nemo should work just fine with extensions of relatively high degree, and on my list above we have degree 8 max.

**Comment by bottine** [comment]
> > > Q(\sqrt{6}) should not be too much trouble
> 
> Not sure even about this! (after a few tries in dim n=3) It works, yes, but finds no _reflective_ form so far.

By "not too much trouble" I only meant computations should be fast enough there. As for reflexivity, who knows :)

> > we will quickly get to the point where the implementation fails miserably
> 
> Why would it fail so badly ? Nemo should work just fine with extensions of relatively high degree, and on my list above we have degree 8 max.

Yes, but for instance listing the possible coefficients of our root's entries amounts to searching short lattice vectors in dimension 8, which is obviously way more complicated than in dimension 2.
Another problem is that for complicated fields, the number of possible root lengths probably becomes big: e.g. for the simple form you gave in the issue, you get ~300 possible lengths!
I don't know if there is a correlation between the degree of the field extension and the possible root lengths, though.
