### ISSUE TITLE
No method found

### ISSUE THREAD

**Issue by sashakolpakov** [bottine/VinbergsAlgorithmNF#6]
On input 

[2  -1          0        0;
-1   2         -ϕ       0;
0   -ϕ        2        -1;
0    0        -1         2]

with ϕ = -sqrt(7)+2

ERROR: LoadError: MethodError: no method matching extend_root_stem(::VinbergData, ::Array{nf_elem,1}, ::Array{nf_elem,1}, ::NfAbsOrdElem{AnticNumberField,nf_elem}, ::nf_elem, ::Tuple{Array{Array{nf_elem,1},1},Array{nf_elem,1},Array{Union{Nothing, Int64},1}}, ::VinbergsAlgorithmNF.BoundedT2ElemsCache)
Closest candidates are:
  extend_root_stem(::VinbergData, ::Array{nf_elem,1}, ::Array{nf_elem,1}, ::Any, ::Any, ::Tuple{Array{Array{nf_elem,1},1},Array{nf_elem,1},Array{Int64,1}}, ::VinbergsAlgorithmNF.BoundedT2ElemsCache)

**Comment by bottine** [comment]
Can you paste the whole session? From launching julia and on?
But I wouldn't use the program too much right now, it seems I messed up quite a lot of stuff in the cone root computation part. I need to figure it out.

**Comment by sashakolpakov** [comment]
[ Info: Toggleable asserts turned off.
[ Info: Basepoint is nf_elem[-1, -2, sqrt(7) + 2, 0]
┌ Warning: Cone roots computation are approximative ⇒ double check the results by hand.
└ @ VinbergsAlgorithmNF ~/.julia/packages/VinbergsAlgorithmNF/6pOZP/src/vinbergs_algo.jl:500
**[ Info: have 0 cone roots**
[ Info: enumerate_k (l=1, k_min=0, k_max=10)
[ Info: enumerate_k (l=sqrt(7) + 3, k_min=0, k_max=10)
[ Info: enumerate_k (l=6*sqrt(7) + 16, k_min=0, k_max=10)
[ Info: enumerate_k (l=-4*sqrt(7) + 11, k_min=0, k_max=10)
[ Info: enumerate_k (l=-sqrt(7) + 5, k_min=0, k_max=10)
[ Info: enumerate_k (l=2*sqrt(7) + 8, k_min=0, k_max=10)
[ Info: enumerate_k (l=3*sqrt(7) + 8, k_min=0, k_max=10)
[ Info: enumerate_k (l=17*sqrt(7) + 45, k_min=0, k_max=10)
[ Info: enumerate_k (l=96*sqrt(7) + 254, k_min=0, k_max=10)
[ Info: enumerate_k (l=sqrt(7) + 4, k_min=0, k_max=10)
[ Info: enumerate_k (l=7*sqrt(7) + 19, k_min=0, k_max=10)
[ Info: enumerate_k (l=40*sqrt(7) + 106, k_min=0, k_max=10)
[ Info: enumerate_k (l=48*sqrt(7) + 127, k_min=0, k_max=10)
[ Info: enumerate_k (l=271*sqrt(7) + 717, k_min=0, k_max=10)
[ Info: enumerate_k (l=1530*sqrt(7) + 4048, k_min=0, k_max=10)
[ Info: enumerate_k (l=20*sqrt(7) + 53, k_min=0, k_max=10)
[ Info: enumerate_k (l=113*sqrt(7) + 299, k_min=0, k_max=10)
[ Info: enumerate_k (l=638*sqrt(7) + 1688, k_min=0, k_max=10)
[ Info: enumerate_k (l=-2*sqrt(7) + 7, k_min=0, k_max=10)
[ Info: enumerate_k (l=sqrt(7) + 7, k_min=0, k_max=10)
[ Info: enumerate_k (l=10*sqrt(7) + 28, k_min=0, k_max=10)
[ Info: enumerate_k (l=-50*sqrt(7) + 133, k_min=0, k_max=10)
[ Info: enumerate_k (l=-50*sqrt(7) + 133, k_min=10, k_max=20)
[ Info: enumerate_k (l=-17*sqrt(7) + 49, k_min=0, k_max=10)
[ Info: enumerate_k (l=-2*sqrt(7) + 28, k_min=0, k_max=10)
[ Info: enumerate_k (l=5*sqrt(7) + 14, k_min=0, k_max=10)
[ Info: enumerate_k (l=29*sqrt(7) + 77, k_min=0, k_max=10)
[ Info: enumerate_k (l=164*sqrt(7) + 434, k_min=0, k_max=10)
[ Info: enumerate_k (l=-sqrt(7) + 14, k_min=0, k_max=10)
[ Info: enumerate_k (l=11*sqrt(7) + 35, k_min=0, k_max=10)
[ Info: enumerate_k (l=68*sqrt(7) + 182, k_min=0, k_max=10)
[ Info: enumerate_k (l=82*sqrt(7) + 217, k_min=0, k_max=10)
[ Info: enumerate_k (l=463*sqrt(7) + 1225, k_min=0, k_max=10)
[ Info: enumerate_k (l=2614*sqrt(7) + 6916, k_min=0, k_max=10)
[ Info: enumerate_k (l=34*sqrt(7) + 91, k_min=0, k_max=10)
[ Info: enumerate_k (l=193*sqrt(7) + 511, k_min=0, k_max=10)
[ Info: enumerate_k (l=1090*sqrt(7) + 2884, k_min=0, k_max=10)
[ Info: next pair is (-1//12*sqrt(7) - 5//24, 6*sqrt(7) + 16) (fake_dist is -1//24*sqrt(7) - 5//48 ≈ 0.006072971293178853)
ERROR: LoadError: MethodError: no method matching extend_root_stem(::VinbergData, ::Array{nf_elem,1}, ::Array{nf_elem,1}, ::NfAbsOrdElem{AnticNumberField,nf_elem}, ::nf_elem, ::Tuple{Array{Array{nf_elem,1},1},Array{nf_elem,1},Array{Union{Nothing, Int64},1}}, ::VinbergsAlgorithmNF.BoundedT2ElemsCache)
Closest candidates are:
  extend_root_stem(::VinbergData, ::Array{nf_elem,1}, ::Array{nf_elem,1}, ::Any, ::Any, ::Tuple{Array{Array{nf_elem,1},1},Array{nf_elem,1},Array{Int64,1}}, ::VinbergsAlgorithmNF.BoundedT2ElemsCache)

**Comment by bottine** [comment]
OK, I'll see what's going on, but this may take a while!
**EDIT:** Actually, this trace is a bit too short for me to reproduce the error and understand what's going on.
If you can reproduce the error, can you share the full content of your julia session, i.e. with you starting julia, defining whatever fields, etc?
